package net.infinitecoder.jplugin;

public class Operators {
    public static String[] operators = {
        "++",
        "--",
        "==",
        "!=",
        ">=",
        "<=",
        "&&",
        "||",
        "<<",
        ">>",
        "::",
        "[]",
        ".",
        "=",
        "+",
        "-",
        "*",
        "/",
        "%",
        ">",
        "<",
        "!",
        "~",
        "&",
        "|",
        "^",
        "[",
        "]",
        "{",
        "}",
        "(",
        ")",
        ",",
        "?",
        ":",
        ";",
    };
}